app/components/Anchor.css.ts
app/components/Anchor.tsx
app/components/Arrow.tsx
app/components/BodyText.css.ts
app/components/EventsList.tsx
app/components/Heading.css.ts
app/components/Heading.tsx
app/components/Layout.tsx
app/routes/about.tsx
app/routes/code-of-conduct.tsx
app/styles.css.ts
cspell.json

Adds in a description and team member names. Introduces style variants for `Anchor` and Heading` to support the added new styles.

feat: filled in About page

---

pnpm-lock.yaml

I am assuming a previous Renovate PR was merged stale (sorry!) and prevents other PRs such as #291 to pass CI. I will be on the lookout for this going forward.

chore(deps): run `pnpm i` to fix lockfile

---

app/routes/about.tsx
cspell.json

Add Jérémie Astori (hey, that's me!) to https://bostonts.club/about > The Team

feat: add Jérémie Astori to `/about` page

---

app/data/events.json

It's happening again! https://www.eventbrite.com/e/boston-ts-club-iv-a-new-type-tickets-945788598157

chore: add 2024-07-25 event

---

app/components/Anchor.css.ts
app/components/Anchor.tsx
app/routes/about.tsx
app/routes/speak.tsx

Also address an oversight at #288.

feat: add link to the Open Collective donation page

---

app/routes/about.tsx

Yay! I am now officially an organizer of Boston TS Club!
🐢

feat: add Xavier Ruiz to `/about` page

---

app/data/events.json
cspell.json

Looking forward to it!
@JoshuaKGoldberg would you mind creating the event on Eventbrite? 🙏
EDIT: Done

feat: add event for the next meetup

---

app/root.tsx

fix: accessibility issue - add missing `lang` attribute on `<html>` element

---

app/routes/about.tsx
cspell.json

feat: add Hadley Garrett to `/about` page

---

app/routes/about.tsx

feat: remove David Blass from the team 😢

---

app/components/AdGrid.tsx
app/routes/ad.tsx

feat: add month / year support for ad page

---

app/data/events.json
cspell.json
cspell.speaker-names.txt
package.json
pnpm-lock.yaml

feat: add event for September 2024

---

app/data/events.json
cspell.json

feat: add October event

---

app/data/events.json

Adding @hadleygarrett's LinkedIn: https://www.linkedin.com/in/hadley-garrett/

feat: add Hadley's LinkedIn for her talk

---

app/routes/about.tsx
cspell.json

feat: add Sahana J Prakash to /about page 

---

app/data/events.json

- Updating the talk title for Pariss Chandler

feat: Update upcoming event title

---

app/data/events.json

feat: add Sean's CloudFlare talk to November event

---

app/data/events.json

feat: add placeholder event for January 2025

---

app/data/events.json
cspell.speaker-names.txt

feat: add Rebecca Miller's talk to the January 16 event

---

app/data/events.json
cspell.json

feat: add February 2025 event

---

app/data/events.json
cspell.speaker-names.txt

feat: add talks for the February 2025 event

---

app/components/Author.tsx
app/components/EventDetails.tsx
app/components/OxfordCommaList.tsx
app/data/events.json
app/schemas.ts

feat: add title to February 2025 talk and support multiple authors

---

app/data/events.json

feat: add placeholder event for April 2025

---

app/data/events.json

fix: rename David's talk

---

app/data/events.json
cspell.json
cspell.speaker-names.txt
package.json
pnpm-lock.yaml

feat: add event for May 2025

---

app/components/EventDetails.tsx
app/data/events.json
app/schemas.ts

feat: add a placeholder event for June 2025 talk and allow for null event link and talks

---

app/data/events.json
cspell.json
cspell.speaker-names.txt

feat: add talks for June 2025 event and placeholder for July 2025 event

---

app/data/events.json
cspell.speaker-names.txt

fix: remove Jainal's talk that was accidentally listed

---

app/data/events.json
cspell.speaker-names.txt

Add Maddy's talk to the August 2025 event

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/01-bug.yml
.github/ISSUE_TEMPLATE/02-documentation.yml
.github/ISSUE_TEMPLATE/03-feature.yml
.github/ISSUE_TEMPLATE/04-tooling.yml
.github/PULL_REQUEST_TEMPLATE.md
README.md
package.json

Noticed when preparing #385 that the CONTRIBUTING link was outdated. And now it's not.
😘

chore: banish josh

---

app/data/events.json

Adds this bit of TypeScript content for the event.

Added August 2025 Monthly TypeScript Tip
